//  StockCatalog.swift — the film and paper library, read from the bundle.
//
//  `Resources/StockCatalog.json` is generated by `Tools/gen-catalog.py` from
//  the engine's profile directory, so the picker cannot list a stock the
//  engine does not have. Regenerate it when a profile is added.

import Foundation

struct Stock: Codable, Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let stage: String          // "filming" | "printing"
    let use: String            // "still" | "cine"
    let type: String?
    let targetPrint: String?
    let hasPreviewLUT: Bool
    let pairedFilm: String?
    let cover: String?
    /// The film gauges the manufacturer made this stock in, ever: `135`,
    /// `120`, `16mm`, `super8`, `35mm_motion` (`Tools/gen-catalog.py`, from
    /// the sourced availability table). Nil when nobody recorded it.
    let formats: [String]?
    /// A black-and-white stock: a film with one silver emulsion, or a silver
    /// paper (the profile's `channel_model` is `bw`). Absent on colour stocks.
    let monochrome: Bool?

    var isMonochrome: Bool { monochrome ?? false }
    var isFilm: Bool { stage == "filming" }

    /// Whether this stock was ever made on the film a Film Edge format runs
    /// on (answer D3): the menu greys the rest. A stock with no record is
    /// not ruled out of anything — an unknown is not a no.
    func isMade(in format: FilmEdgeFormat) -> Bool {
        guard let formats else { return true }
        // 35 mm motion stock is the same film as 135, loaded into cassettes
        // by hand or by a respooler, so a cine negative is not ruled out of
        // the 135 formats. It carries no DX code and the engine prints none.
        if format.gauge == "135", formats.contains("35mm_motion") { return true }
        return formats.contains(format.gauge)
    }
    var isPaper: Bool { stage == "printing" }
    var isCine: Bool { use == "cine" }
    /// A reversal (slide) film: Provia, Velvia, Ektachrome, Kodachrome.
    ///
    /// The catalogue has carried this since it was generated — `type` is
    /// `"positive"` or `"negative"` and the four slide films are the ones
    /// with no `targetPrint` — and nothing read it. A positive is already a
    /// viewable image, so printing one onto a paper stock is an operation the
    /// engine performs happily and nobody wants.
    var isPositive: Bool { type == "positive" }
    var brand: String { name.split(separator: " ").first.map(String.init) ?? "" }
    var coverURL: URL? {
        cover.flatMap { StockCatalog.bundle.url(forResource: $0, withExtension: nil, subdirectory: "Resources/FilmCovers") }
    }
}

struct StockCatalog: Sendable {
    let stocks: [Stock]

    /// The bundle that carries Resources/: the app, or the test bundle.
    static var bundle: Bundle { Bundle(for: BundleToken.self) }
    private final class BundleToken {}

    static let shared: StockCatalog = {
        let url = bundle.url(forResource: "StockCatalog", withExtension: "json", subdirectory: "Resources")
        if let url, let data = try? Data(contentsOf: url),
           let decoded = try? JSONDecoder().decode(Wrapper.self, from: data) {
            // Black and white is listed only where it is on offer.
            return StockCatalog(stocks: decoded.stocks.filter { FeatureFlags.blackAndWhite || !$0.isMonochrome })
        }
        return StockCatalog(stocks: [])
    }()

    private struct Wrapper: Decodable { let stocks: [Stock] }

    var films: [Stock] { stocks.filter(\.isFilm) }
    var papers: [Stock] { stocks.filter(\.isPaper) }
    func stock(_ id: String) -> Stock? { stocks.first { $0.id == id } }

    /// `Stock.isMade(in:)` by id; an id the catalogue does not know rules
    /// nothing out.
    func isMade(_ id: String, in format: FilmEdgeFormat) -> Bool {
        stock(id)?.isMade(in: format) ?? true
    }

    /// Films in the order the picker shows them: still first, brand-grouped,
    /// then cine. Within a brand the order is the catalog's (alphabetical).
    var filmsForPicker: [Stock] {
        let still = films.filter { !$0.isCine }
        let cine = films.filter(\.isCine)
        return still + cine
    }

    /// Films grouped as v3 draws them: **Positive**, then **Negative**.
    ///
    /// Grouped on `type`, which the catalogue has carried since it was
    /// generated — not on the name and not on the artwork's order, which is
    /// handoff §8.6's requirement. Within each group `filmsForPicker`'s order
    /// is kept, so a cine stock still follows the stills of its group rather
    /// than being hoisted.
    ///
    /// The whole catalogue comes back: v3's illustration shows 3 positive and
    /// 4 negative rows, and those are the counts of a *viewport*, not a
    /// filter.
    var filmGroups: [(title: String, films: [Stock])] {
        let ordered = filmsForPicker
        var groups = [("Positive", ordered.filter(\.isPositive)),
                      ("Negative", ordered.filter { !$0.isPositive && !$0.isMonochrome })]
        // A third group, and only when the catalogue has any: a black-and-white
        // negative prints on a different paper and takes a lens filter, so it
        // is not one more row among the colour negatives.
        let mono = ordered.filter { !$0.isPositive && $0.isMonochrome }
        if !mono.isEmpty { groups.append(("Black & White", mono)) }
        return groups
    }

    /// Papers grouped for the picker: Still, then Cine.
    var paperGroups: [(title: String, papers: [Stock])] {
        [("Still", papers.filter { !$0.isCine }), ("Cine", papers.filter(\.isCine))]
    }

    /// Whether `paper` is the declared target of `film` — an honest pairing
    /// versus an approximation (API-SPEC §2's pairing note).
    func isDeclaredPairing(film: String, paper: String) -> Bool {
        stock(film)?.targetPrint == paper
    }

    /// Whether `paper` can print `film` at all: silver film on silver paper,
    /// colour on colour. A black-and-white negative on a colour paper prints
    /// orange (no filter pack exists for the pair), and the Multigrade
    /// profile's three emulsions are a contrast control, not a colour
    /// response. An id the catalogue does not know rules nothing out.
    func canPrint(film: String, on paper: String) -> Bool {
        guard let f = stock(film), let p = stock(paper) else { return true }
        return f.isMonochrome == p.isMonochrome
    }
}
